### ISSUE TITLE
Decide where to host the website (vercel or github pages probably?)

### ISSUE THREAD

**Issue by Sergih28** [Sergih28/groc#56]
Look specifically to host an Astro project.

**Comment by ehdlg** [comment]
@Sergih28 
GitHub Pages stands out due to its simplicity, cost-free setup, and seamless integration with Git repositories. Especially suited for static websites with minimal JavaScript, it offers an uncomplicated environment for projects requiring straightforward hosting without usage limitations. While Vercel provides more extensive language and framework support, GitHub Pages' ease of use and compatibility with simple static sites makes it a strong contender for initial hosting considerations.
